kind: pipeline
type: docker
name: default
steps:
  - name: Install Dependencies
    image: node:latest
    commands:
      - npm install
  - name: Build
    image: node:latest
    commands:
      - npm run build
    environment:
      CI: "false"
    depends_on:
      - Install Dependencies
  - name: Publish
    image: patrcloud/cli:latest
    commands:
      - patr login -u arjun.vc -p Vicara@123
      - patr site upload --site ./build --name test-site
    environment:
      PASSWORD: Vicara@123
      USERNAME: arjun.vc
    depends_on:
      - Build
