kind: pipeline
type: docker
name: default
steps:
  - name: Install Dependency
    image: node:latest
    commands:
      - npm install
  - name: Build
    image: node:latest
    commands:
      - npm run build
    depends_on:
      - Install Dependency
  - name: Publish
    image: node:latest
    commands:
      - node publish.js
    depends_on:
      - Build
