kind: pipeline
type: docker
name: default
steps:
  - name: Install Dependencies
    image: node:latest
    commands:
      - npm install
    next: Build
  - name: Build
    image: node:latest
    commands:
      - npm run build
    environment:
      CI: "false"
